//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.21 at 11:25:00 AM IST 
//


package com.payment.ncresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="orderID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PAYID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PAYIDSUB" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NCSTATUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NCERROR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NCERRORPLUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ACCEPTANCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BRAND" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CARDNO" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ALIAS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ED" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SCORING" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SCO_CATEGORY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ncresponse")
public class Ncresponse {

    @XmlAttribute(name = "orderID")
    protected String orderID;
    @XmlAttribute(name = "PAYID")
    protected String payid;
    @XmlAttribute(name = "PAYIDSUB")
    protected String payidsub;
    @XmlAttribute(name = "NCSTATUS")
    protected String ncstatus;
    @XmlAttribute(name = "NCERROR")
    protected String ncerror;
    @XmlAttribute(name = "NCERRORPLUS")
    protected String ncerrorplus;
    @XmlAttribute(name = "ACCEPTANCE")
    protected String acceptance;
    @XmlAttribute(name = "STATUS")
    protected String status;
    @XmlAttribute(name = "amount")
    protected String amount;
    @XmlAttribute(name = "currency")
    protected String currency;
    @XmlAttribute(name = "PM")
    protected String pm;
    @XmlAttribute(name = "BRAND")
    protected String brand;
    @XmlAttribute(name = "CARDNO")
    protected String cardno;
    @XmlAttribute(name = "ALIAS")
    protected String alias;
    @XmlAttribute(name = "ED")
    protected String ed;
    @XmlAttribute(name = "SCORING")
    protected String scoring;
    @XmlAttribute(name = "SCO_CATEGORY")
    protected String scocategory;

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the payid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYID() {
        return payid;
    }

    /**
     * Sets the value of the payid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYID(String value) {
        this.payid = value;
    }

    /**
     * Gets the value of the payidsub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYIDSUB() {
        return payidsub;
    }

    /**
     * Sets the value of the payidsub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYIDSUB(String value) {
        this.payidsub = value;
    }

    /**
     * Gets the value of the ncstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCSTATUS() {
        return ncstatus;
    }

    /**
     * Sets the value of the ncstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCSTATUS(String value) {
        this.ncstatus = value;
    }

    /**
     * Gets the value of the ncerror property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCERROR() {
        return ncerror;
    }

    /**
     * Sets the value of the ncerror property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCERROR(String value) {
        this.ncerror = value;
    }

    /**
     * Gets the value of the ncerrorplus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCERRORPLUS() {
        return ncerrorplus;
    }

    /**
     * Sets the value of the ncerrorplus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCERRORPLUS(String value) {
        this.ncerrorplus = value;
    }

    /**
     * Gets the value of the acceptance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCEPTANCE() {
        return acceptance;
    }

    /**
     * Sets the value of the acceptance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCEPTANCE(String value) {
        this.acceptance = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the pm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPM() {
        return pm;
    }

    /**
     * Sets the value of the pm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPM(String value) {
        this.pm = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRAND() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRAND(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the cardno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCARDNO() {
        return cardno;
    }

    /**
     * Sets the value of the cardno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCARDNO(String value) {
        this.cardno = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALIAS() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALIAS(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the ed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getED() {
        return ed;
    }

    /**
     * Sets the value of the ed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setED(String value) {
        this.ed = value;
    }

    /**
     * Gets the value of the scoring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCORING() {
        return scoring;
    }

    /**
     * Sets the value of the scoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCORING(String value) {
        this.scoring = value;
    }

    /**
     * Gets the value of the scocategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCOCATEGORY() {
        return scocategory;
    }

    /**
     * Sets the value of the scocategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCOCATEGORY(String value) {
        this.scocategory = value;
    }

}
