--------------------------------------------------------
--  DDL for Table TR_TRN
--------------------------------------------------------
  DROP TABLE TR_TRN;
  CREATE TABLE "TR_TRN" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_OPR" VARCHAR2(10 BYTE), 
	"TY_TRN" VARCHAR2(20 BYTE), 
	"TS_TM_SRT" TIMESTAMP (9), 
	"TS_TRN_BGN" TIMESTAMP (9), 
	"TS_TRN_END" TIMESTAMP (9), 
	"FL_TRG_TRN" CHAR(1 BYTE) DEFAULT '0', 
	"FL_KY_OFL" CHAR(1 BYTE) DEFAULT '0', 
	"SC_TRN" NUMBER(*,0) DEFAULT 2, 
	"ID_EM" VARCHAR2(10 BYTE), 
	"INF_CT" VARCHAR2(120 BYTE), 
	"TY_INF_CT" NUMBER(*,0) DEFAULT 0, 
	"ID_RPSTY_TND" VARCHAR2(10 BYTE), 
	"ID_CNY_ICD" NUMBER(*,0), 
	"ID_TLOG_BTCH" NUMBER(*,0) DEFAULT -1, 
	"ID_BTCH_ARCH" VARCHAR2(14 BYTE) DEFAULT '-1', 
	"ID_RTLOG_BTCH" VARCHAR2(14 BYTE) DEFAULT '-1', 
	"ID_BTCH_INV_RESV" VARCHAR2(14 BYTE) DEFAULT '-1', 
	"SC_PST_PRCS" NUMBER(*,0) DEFAULT 0, 
	"FL_TRE_TRN" CHAR(1 BYTE) DEFAULT '0', 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9), 
	"FL_SLS_ASSC_MDF" CHAR(1 BYTE) DEFAULT '0'
   );
 

   COMMENT ON COLUMN "TR_TRN"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_TRN"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_TRN"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_TRN"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_TRN"."ID_OPR" IS 'OperatorID';
 
   COMMENT ON COLUMN "TR_TRN"."TY_TRN" IS 'TransactionTypeCode';
 
   COMMENT ON COLUMN "TR_TRN"."TS_TM_SRT" IS 'WorkstationStartDateTimestamp';
 
   COMMENT ON COLUMN "TR_TRN"."TS_TRN_BGN" IS 'TransactionBeginDateTimestamp';
 
   COMMENT ON COLUMN "TR_TRN"."TS_TRN_END" IS 'TransactionEndDateTimestamp';
 
   COMMENT ON COLUMN "TR_TRN"."FL_TRG_TRN" IS 'TransactionTrainingFlag';
 
   COMMENT ON COLUMN "TR_TRN"."FL_KY_OFL" IS 'TransactionKeyedOfflineFlag';
 
   COMMENT ON COLUMN "TR_TRN"."SC_TRN" IS 'TransactionStatusCode';
 
   COMMENT ON COLUMN "TR_TRN"."ID_EM" IS 'SalesAssociateID';
 
   COMMENT ON COLUMN "TR_TRN"."INF_CT" IS 'CustomerInfo';
 
   COMMENT ON COLUMN "TR_TRN"."TY_INF_CT" IS 'CustomerInfoType';
 
   COMMENT ON COLUMN "TR_TRN"."ID_RPSTY_TND" IS 'TenderRepositoryID';
 
   COMMENT ON COLUMN "TR_TRN"."ID_CNY_ICD" IS 'CurrencyID';
 
   COMMENT ON COLUMN "TR_TRN"."ID_TLOG_BTCH" IS 'TransactionTLogBatchID';
 
   COMMENT ON COLUMN "TR_TRN"."ID_BTCH_ARCH" IS 'TransactionArchiveBatchID';
 
   COMMENT ON COLUMN "TR_TRN"."ID_RTLOG_BTCH" IS 'TransactionRTLogBatchID';
 
   COMMENT ON COLUMN "TR_TRN"."ID_BTCH_INV_RESV" IS 'TransactionInventoryReservationBatchID';
 
   COMMENT ON COLUMN "TR_TRN"."SC_PST_PRCS" IS 'TransactionPostProcessingStatusCode';
 
   COMMENT ON COLUMN "TR_TRN"."FL_TRE_TRN" IS 'TransactionReentryFlag';
 
   COMMENT ON COLUMN "TR_TRN"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "TR_TRN"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON COLUMN "TR_TRN"."FL_SLS_ASSC_MDF" IS 'SalesAssociateModifiedFlag';
 
   COMMENT ON TABLE "TR_TRN"  IS 'Transaction';
 
   ALTER TABLE "TR_TRN" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN");
   

--------------------------------------------------------
--  DDL for Table TR_RTL
--------------------------------------------------------
  DROP TABLE TR_RTL;
  CREATE TABLE "TR_RTL" 
   (	"ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_CT" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ID_REGISTRY" VARCHAR2(14 BYTE), 
	"ID_LY" VARCHAR2(30 BYTE), 
	"ID_ORD" VARCHAR2(50 BYTE), 
	"IN_RNG_ELPSD" NUMBER(5,0) DEFAULT 0, 
	"IN_TND_ELPSD" NUMBER(5,0) DEFAULT 0, 
	"IN_ELPSD_IDL" NUMBER(5,0) DEFAULT 0, 
	"IN_LCK_ELPSD" NUMBER(5,0) DEFAULT 0, 
	"QU_ITM_LN_SC" NUMBER(7,0) DEFAULT 0, 
	"PE_ITM_LN_SC" NUMBER(5,2) DEFAULT 0, 
	"QU_ITM_LN_KY" NUMBER(7,0) DEFAULT 0, 
	"PE_ITM_LN_KY" NUMBER(5,2) DEFAULT 0, 
	"QU_DPT_KY" NUMBER(7,0) DEFAULT 0, 
	"PE_DPT_KY" NUMBER(5,2) DEFAULT 0, 
	"MO_SLS_TOT" NUMBER(13,2) DEFAULT 0, 
	"MO_DSC_TOT" NUMBER(13,2) DEFAULT 0, 
	"MO_TAX_TOT" NUMBER(13,2) DEFAULT 0, 
	"MO_NT_TOT" NUMBER(13,2) DEFAULT 0, 
	"MO_TND_TOT" NUMBER(13,2) DEFAULT 0, 
	"ID_EM" VARCHAR2(10 BYTE), 
	"RC_RSN_SPN" VARCHAR2(10 BYTE), 
	"CNT_SND_PKG" NUMBER(*,0) DEFAULT 0, 
	"TY_SND_CT" CHAR(1 BYTE), 
	"FL_SND_CT_PHY" CHAR(1 BYTE), 
	"TR_LVL_SND" CHAR(1 BYTE), 
	"TY_ID_PRSL_RQ" VARCHAR2(20 BYTE), 
	"ID_NCRPT_PRSL" VARCHAR2(500 BYTE), 
	"ID_MSK_PRSL" VARCHAR2(20 BYTE), 
	"ST_PRSL" VARCHAR2(20 BYTE), 
	"CO_PRSL" VARCHAR2(20 BYTE), 
	"ID_IRS_CT" VARCHAR2(14 BYTE), 
	"DT_AG_RST_DOB" DATE, 
	"MO_TAX_INC_TOT" NUMBER(13,2) DEFAULT 0, 
	"MO_DS_APLD" NUMBER(13,2) DEFAULT 0, 
	"RTN_TKT_NO" VARCHAR2(40 BYTE), 
	"FL_RCP_GF_TRN" CHAR(1 BYTE) DEFAULT '0', 
	"ID_ORD_EXT" VARCHAR2(50 BYTE), 
	"ID_ORD_EXT_NMB" VARCHAR2(250 BYTE), 
	"FL_CT_AZN_RQ" CHAR(1 BYTE) DEFAULT '0', 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9), 
	"FL_PT_PRDV" CHAR(1 BYTE), 
	"STR_CRDT_RFND_AMT" NUMBER(13,2), 
	"NBTY_VAT_RECPT_FLAG" VARCHAR2(1 BYTE) DEFAULT 0
   );
 

   COMMENT ON COLUMN "TR_RTL"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_RTL"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_RTL"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_RTL"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_RTL"."ID_CT" IS 'CustomerID';
 
   COMMENT ON COLUMN "TR_RTL"."ID_REGISTRY" IS 'GiftRegistryID';
 
   COMMENT ON COLUMN "TR_RTL"."ID_LY" IS 'LayawayID';
 
   COMMENT ON COLUMN "TR_RTL"."ID_ORD" IS 'OrderID';
 
   COMMENT ON COLUMN "TR_RTL"."IN_RNG_ELPSD" IS 'RingElapsedTime';
 
   COMMENT ON COLUMN "TR_RTL"."IN_TND_ELPSD" IS 'TenderElapsedTime';
 
   COMMENT ON COLUMN "TR_RTL"."IN_ELPSD_IDL" IS 'IdleElapsedTime';
 
   COMMENT ON COLUMN "TR_RTL"."IN_LCK_ELPSD" IS 'LockElapsedTime';
 
   COMMENT ON COLUMN "TR_RTL"."QU_ITM_LN_SC" IS 'LineItemsScannedCount';
 
   COMMENT ON COLUMN "TR_RTL"."PE_ITM_LN_SC" IS 'LineItemsScannedPercent';
 
   COMMENT ON COLUMN "TR_RTL"."QU_ITM_LN_KY" IS 'LineItemsKeyedCount';
 
   COMMENT ON COLUMN "TR_RTL"."PE_ITM_LN_KY" IS 'LineItemsKeyedPercent';
 
   COMMENT ON COLUMN "TR_RTL"."QU_DPT_KY" IS 'KeyDepartmentCount';
 
   COMMENT ON COLUMN "TR_RTL"."PE_DPT_KY" IS 'KeyDepartmentPercent';
 
   COMMENT ON COLUMN "TR_RTL"."MO_SLS_TOT" IS 'TransactionSalesTotal';
 
   COMMENT ON COLUMN "TR_RTL"."MO_DSC_TOT" IS 'TransactionDiscountTotal';
 
   COMMENT ON COLUMN "TR_RTL"."MO_TAX_TOT" IS 'TransactionTaxTotal';
 
   COMMENT ON COLUMN "TR_RTL"."MO_NT_TOT" IS 'TransactionNetTotal';
 
   COMMENT ON COLUMN "TR_RTL"."MO_TND_TOT" IS 'TransactionTenderTotal';
 
   COMMENT ON COLUMN "TR_RTL"."ID_EM" IS 'EmployeeID';
 
   COMMENT ON COLUMN "TR_RTL"."RC_RSN_SPN" IS 'SuspendedTransactionReasonCode';
 
   COMMENT ON COLUMN "TR_RTL"."CNT_SND_PKG" IS 'SendPackageCount';
 
   COMMENT ON COLUMN "TR_RTL"."TY_SND_CT" IS 'SendCustomerType';
 
   COMMENT ON COLUMN "TR_RTL"."FL_SND_CT_PHY" IS 'FlagSendCustomerPhysicallyPresent';
 
   COMMENT ON COLUMN "TR_RTL"."TR_LVL_SND" IS 'TransactionLevelSend';
 
   COMMENT ON COLUMN "TR_RTL"."TY_ID_PRSL_RQ" IS 'PersonalIDRequiredType';
 
   COMMENT ON COLUMN "TR_RTL"."ID_NCRPT_PRSL" IS 'EncryptedPersonalIDNumber';
 
   COMMENT ON COLUMN "TR_RTL"."ID_MSK_PRSL" IS 'MaskedPersonalIDNumber';
 
   COMMENT ON COLUMN "TR_RTL"."ST_PRSL" IS 'PersonalIDState';
 
   COMMENT ON COLUMN "TR_RTL"."CO_PRSL" IS 'PersonalIDCountry';
 
   COMMENT ON COLUMN "TR_RTL"."ID_IRS_CT" IS 'IRSCustomerID';
 
   COMMENT ON COLUMN "TR_RTL"."DT_AG_RST_DOB" IS 'AgeRestrictionDateOfBirth';
 
   COMMENT ON COLUMN "TR_RTL"."MO_TAX_INC_TOT" IS 'TransactionInclusiveTaxTotal';
 
   COMMENT ON COLUMN "TR_RTL"."MO_DS_APLD" IS 'AmountDepositApplied';
 
   COMMENT ON COLUMN "TR_RTL"."RTN_TKT_NO" IS 'ReturnTicketNumber';
 
   COMMENT ON COLUMN "TR_RTL"."FL_RCP_GF_TRN" IS 'TransactionGiftReceiptFlag';
 
   COMMENT ON COLUMN "TR_RTL"."ID_ORD_EXT" IS 'ExternalOrderID';
 
   COMMENT ON COLUMN "TR_RTL"."ID_ORD_EXT_NMB" IS 'ExternalOrderNumber';
 
   COMMENT ON COLUMN "TR_RTL"."FL_CT_AZN_RQ" IS 'CustomerSignatureRequiredFlag';
 
   COMMENT ON COLUMN "TR_RTL"."TS_CRT_RCRD" IS 'RecordCreationTimestamp';
 
   COMMENT ON COLUMN "TR_RTL"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON COLUMN "TR_RTL"."STR_CRDT_RFND_AMT" IS 'StoreCreditRefundAmount';
 
   COMMENT ON COLUMN "TR_RTL"."NBTY_VAT_RECPT_FLAG" IS 'VAT Receipt Printed';
 
   COMMENT ON TABLE "TR_RTL"  IS 'RetailTransaction';

   ALTER TABLE "TR_RTL" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN");



   --------------------------------------------------------
--  DDL for Table TR_LTM_DSC
--------------------------------------------------------
  DROP TABLE TR_LTM_DSC;
  CREATE TABLE "TR_LTM_DSC" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"TY_DSC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RC_DSC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MO_DSC" NUMBER(14,3) DEFAULT 0, 
	"PE_DSC" NUMBER(5,2) DEFAULT 0, 
	"FL_DSC_ENA" CHAR(1 BYTE) NOT NULL ENABLE, 
	"LU_BAS_ASGN" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"FL_DL_ADVN_APLY" CHAR(1 BYTE) DEFAULT '0', 
	"ID_RU_DSC" NUMBER(*,0), 
	"ID_DSC_REF" VARCHAR2(255 BYTE), 
	"CO_ID_DSC_REF" VARCHAR2(2 BYTE) DEFAULT 'UN', 
	"ID_DSC_EM" VARCHAR2(10 BYTE), 
	"ID_PRM" NUMBER(*,0) DEFAULT 0, 
	"ID_PRM_CMP" NUMBER(*,0) DEFAULT 0, 
	"ID_PRM_CMP_DTL" NUMBER(*,0) DEFAULT 0, 
	"ID_PRCGP" NUMBER(*,0), 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "TR_LTM_DSC"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."TY_DSC" IS 'DiscountType';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."RC_DSC" IS 'DiscountReasonCode';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."MO_DSC" IS 'DiscountAmount';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."PE_DSC" IS 'DiscountPercent';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."FL_DSC_ENA" IS 'DiscountEnabledFlag';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."LU_BAS_ASGN" IS 'DiscountAssignmentBasis';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."FL_DL_ADVN_APLY" IS 'AdvancedDealAppliedFlag';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."ID_RU_DSC" IS 'DiscountDerivationRuleID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."ID_DSC_REF" IS 'DiscountReferenceID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."CO_ID_DSC_REF" IS 'DiscountReferenceTypeCode';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."ID_DSC_EM" IS 'EmployeeDiscountEmployeeID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."ID_PRM" IS 'PromotionID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."ID_PRM_CMP" IS 'PromotionComponentID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."ID_PRM_CMP_DTL" IS 'PromotionComponentDetailID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."ID_PRCGP" IS 'PricingGroupID';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."TS_CRT_RCRD" IS 'RecordCreationTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_DSC"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "TR_LTM_DSC"  IS 'DiscountLineItem';

   ALTER TABLE "TR_LTM_DSC" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");

   
   
   
   
   
--------------------------------------------------------
--  DDL for Table TR_LTM_SLS_RTN
--------------------------------------------------------
  DROP TABLE TR_LTM_SLS_RTN;
  CREATE TABLE "TR_LTM_SLS_RTN" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_REGISTRY" VARCHAR2(14 BYTE), 
	"ID_GP_TX" NUMBER(*,0) DEFAULT 0, 
	"ID_DPT_POS" VARCHAR2(14 BYTE), 
	"ID_ITM_POS" VARCHAR2(14 BYTE), 
	"ID_ITM" VARCHAR2(14 BYTE), 
	"QU_ITM_LM_RTN_SLS" NUMBER(9,2) DEFAULT 0, 
	"MO_EXTN_LN_ITM_RTN" NUMBER(13,2) DEFAULT 0, 
	"MO_EXTN_DSC_LN_ITM" NUMBER(13,2) DEFAULT 0, 
	"MO_VAT_LN_ITM_RTN" NUMBER(13,2) DEFAULT 0, 
	"MO_FE_RSTK" NUMBER(13,2), 
	"FL_RTN_MR" CHAR(1 BYTE) DEFAULT '0', 
	"RC_RTN_MR" VARCHAR2(20 BYTE), 
	"FL_RFD_SV" CHAR(1 BYTE) DEFAULT '0', 
	"RC_RFD_SV" VARCHAR2(2 BYTE), 
	"LU_MTH_ID_ENR" VARCHAR2(4 BYTE), 
	"LU_ENTR_RT_PRC" VARCHAR2(4 BYTE), 
	"LU_PRC_RT_DRVN" VARCHAR2(4 BYTE), 
	"QU_ITM_LN_RTN" NUMBER(9,2) DEFAULT 0, 
	"ID_TRN_ORG" VARCHAR2(20 BYTE), 
	"DC_DY_BSN_ORG" VARCHAR2(10 BYTE), 
	"AI_LN_ITM_ORG" NUMBER(*,0) DEFAULT -1, 
	"ID_STR_RT_ORG" VARCHAR2(5 BYTE), 
	"ID_NMB_SRZ" VARCHAR2(40 BYTE), 
	"LU_KT_ST" VARCHAR2(20 BYTE) DEFAULT '0', 
	"LU_KT_HDR_RFN_ID" NUMBER(*,0), 
	"ID_CLN" VARCHAR2(14 BYTE), 
	"FL_SND" CHAR(1 BYTE) DEFAULT '0', 
	"CNT_SND_LAB" NUMBER(*,0) DEFAULT 0, 
	"ID_SHP_MTH" NUMBER(*,0), 
	"SPL_INSTRC" VARCHAR2(250 BYTE), 
	"ADS_SHP" VARCHAR2(240 BYTE), 
	"FL_RCV_GF" CHAR(1 BYTE) DEFAULT '0', 
	"OR_ID_REF" NUMBER(*,0) DEFAULT 0,
	"FL_VD_LN_ITM" CHAR(1 BYTE) DEFAULT '0', 
	"FL_MDFR_RTL_PRC" CHAR(1 BYTE) DEFAULT '0', 
	"ED_SZ" VARCHAR2(10 BYTE), 
	"FL_ITM_PRC_ADJ" CHAR(1 BYTE) DEFAULT '0', 
	"LU_PRC_ADJ_RFN_ID" NUMBER(*,0), 
	"FL_RLTD_ITM_RTN" CHAR(1 BYTE), 
	"AI_LN_ITM_RLTD" NUMBER(*,0), 
	"FL_RLTD_ITM_RM" CHAR(1 BYTE) DEFAULT '1' NOT NULL ENABLE, 
	"FL_RTRVD_TRN" CHAR(1 BYTE) DEFAULT '0', 
	"MO_TAX_INC_LN_ITM_RTN" NUMBER(13,2) DEFAULT 0, 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9), 
	"FL_SLS_ASSC_MDF" CHAR(1 BYTE) DEFAULT '0', 
	"MO_PRN_PRC" NUMBER(8,2) DEFAULT 0, 
	"DE_ITM_SHRT_RCPT" VARCHAR2(120 BYTE) DEFAULT '', 
	"DE_ITM_LCL" VARCHAR2(10 BYTE) DEFAULT 'en', 
	"FL_FE_RSTK" CHAR(1 BYTE) DEFAULT '0', 
	"LU_HRC_MR_LV" VARCHAR2(4 BYTE) DEFAULT 'UNDF', 
	"FL_ITM_SZ_REQ" CHAR(1 BYTE) DEFAULT '0', 
	"TY_ITM" NUMBER(*,0) DEFAULT 1, 
	"LU_UOM_SLS" VARCHAR2(20 BYTE) DEFAULT 'UN', 
	"FL_RTN_PRH" CHAR(1 BYTE) DEFAULT '0', 
	"FL_DSC_EM_ALW" CHAR(1 BYTE) DEFAULT '1', 
	"FL_TX" CHAR(1 BYTE) DEFAULT '1', 
	"FL_ITM_DSC" CHAR(1 BYTE) DEFAULT '1', 
	"FL_ITM_DSC_DMG" CHAR(1 BYTE) DEFAULT '1', 
	"ID_MRHRC_GP" VARCHAR2(14 BYTE), 
	"ID_ITM_MF_UPC" VARCHAR2(14 BYTE), 
	"NBTY_FL_PR_ITM" NUMBER DEFAULT 0, 
	"WEB_LN_ITM_STS" NUMBER DEFAULT 0, 
	"WEB_LN_ITM_SEQ" NUMBER,
	"WEB_LN_ITM_BSN_DT" VARCHAR2(10 BYTE),
	"WEB_ORDER_NUMBER" VARCHAR2(50 BYTE)
   );
 

   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_REGISTRY" IS 'GiftRegistryID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_GP_TX" IS 'TaxGroupID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_DPT_POS" IS 'POSDepartmentID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_ITM_POS" IS 'POSItemID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_ITM" IS 'ItemID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."QU_ITM_LM_RTN_SLS" IS 'SaleReturnLineItemQuantity';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."MO_EXTN_LN_ITM_RTN" IS 'SaleReturnLineItemExtendedAmount';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."MO_EXTN_DSC_LN_ITM" IS 'SaleReturnLineItemExtendedDiscountedAmount';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."MO_VAT_LN_ITM_RTN" IS 'SaleReturnLineItemVatAmount';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."MO_FE_RSTK" IS 'SaleReturnLineItemRestockingFeeAmount';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_RTN_MR" IS 'MerchandiseReturnFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."RC_RTN_MR" IS 'MerchandiseReturnReasonCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_RFD_SV" IS 'ServiceRefundFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."RC_RFD_SV" IS 'ServiceRefundReasonCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."LU_MTH_ID_ENR" IS 'ItemIDEntryMethodCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."LU_ENTR_RT_PRC" IS 'ItemSellUnitRetailPriceEntryMethodCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."LU_PRC_RT_DRVN" IS 'ItemSellUnitRetailPriceDerivationMethodCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."QU_ITM_LN_RTN" IS 'SaleReturnLineItemReturnQuantity';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_TRN_ORG" IS 'POSOriginalTransactionID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."DC_DY_BSN_ORG" IS 'OriginalBusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."AI_LN_ITM_ORG" IS 'OriginalRetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_STR_RT_ORG" IS 'OriginalRetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_NMB_SRZ" IS 'SerialNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."LU_KT_ST" IS 'KitSetCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."LU_KT_HDR_RFN_ID" IS 'ItemKitHeaderReferenceID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_CLN" IS 'ItemCollectionID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_SND" IS 'SendFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."CNT_SND_LAB" IS 'SendLabelCount';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_SHP_MTH" IS 'ShippingMethodID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."SPL_INSTRC" IS 'SpecialInstruction';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ADS_SHP" IS 'ShippingAddress';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_RCV_GF" IS 'GiftReceiptFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."OR_ID_REF" IS 'OrderLineItemReference';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_VD_LN_ITM" IS 'LineItemVoidedFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_MDFR_RTL_PRC" IS 'RetailPriceModifiedFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ED_SZ" IS 'SizeCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_ITM_PRC_ADJ" IS 'PriceAdjustmentLineItemFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."LU_PRC_ADJ_RFN_ID" IS 'PriceAdjustmentReferenceID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_RLTD_ITM_RTN" IS 'ReturnRelatedItemFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."AI_LN_ITM_RLTD" IS 'RelatedItemTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_RLTD_ITM_RM" IS 'RemoveRelatedItemFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_RTRVD_TRN" IS 'ItemFromRetrievedTransactionFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."MO_TAX_INC_LN_ITM_RTN" IS 'SaleReturnLineItemInclusiveTaxAmount';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_SLS_ASSC_MDF" IS 'SalesAssociateModifiedFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."MO_PRN_PRC" IS 'PermanentRetailPriceAtTimeOfSale';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."DE_ITM_SHRT_RCPT" IS 'ItemDescriptionUsedOnCustomerReceipt';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."DE_ITM_LCL" IS 'ItemDescriptionLocale';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_FE_RSTK" IS 'RestockingFeeFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."LU_HRC_MR_LV" IS 'MerchandiseHierarchyLevelCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_ITM_SZ_REQ" IS 'ItemSizeRequiredFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."TY_ITM" IS 'TypeCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."LU_UOM_SLS" IS 'StockItemSaleUnitOfMeasureCode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_RTN_PRH" IS 'ItemReturnProhibited';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_DSC_EM_ALW" IS 'ItemEmployeeDiscountAllowed';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_TX" IS 'ItemTaxableFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_ITM_DSC" IS 'DiscountFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."FL_ITM_DSC_DMG" IS 'DamageDiscountFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_MRHRC_GP" IS 'MerchandiseHierarchyGroupID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."ID_ITM_MF_UPC" IS 'ManufacturerItemUPC';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."NBTY_FL_PR_ITM" IS 'PromotionItemFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."WEB_LN_ITM_STS" IS 'WebOrderItemStatus';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."WEB_LN_ITM_SEQ" IS 'WebOrderItemSequenceNo';
   
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."WEB_LN_ITM_BSN_DT" IS 'WebOrderItemBusinessDate';
   
   COMMENT ON COLUMN "TR_LTM_SLS_RTN"."WEB_ORDER_NUMBER" IS 'WebOrderNumber';
   
   COMMENT ON TABLE "TR_LTM_SLS_RTN"  IS 'SaleReturnLineItem';

   ALTER TABLE "TR_LTM_SLS_RTN" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");
   


--------------------------------------------------------
--  DDL for Table TR_LTM_RTL_TRN
--------------------------------------------------------
  DROP TABLE TR_LTM_RTL_TRN;
  CREATE TABLE "TR_LTM_RTL_TRN" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"TY_LN_ITM" VARCHAR2(20 BYTE), 
	"TS_LN_ITM_BGN" TIMESTAMP (9), 
	"TS_LN_ITM_END" TIMESTAMP (9), 
	"FL_VD_LN_ITM" CHAR(1 BYTE) DEFAULT '0', 
	"AI_LN_ITM_VD" NUMBER(*,0) DEFAULT -1, 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."TY_LN_ITM" IS 'RetailTransactionLineItemTypeCode';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."TS_LN_ITM_BGN" IS 'RetailTransactionLineItemBeginDateTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."TS_LN_ITM_END" IS 'RetailTransactionLineItemEndDateTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."FL_VD_LN_ITM" IS 'RetailTransactionLineItemVoidFlag';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."AI_LN_ITM_VD" IS 'VoidedLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_RTL_TRN"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "TR_LTM_RTL_TRN"  IS 'RetailTransactionLineItem';
  
   ALTER TABLE "TR_LTM_RTL_TRN" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");
  


   
   
--------------------------------------------------------
--  DDL for Table TR_LTM_SLS_RTN_ORD
--------------------------------------------------------
  DROP TABLE TR_LTM_SLS_RTN_ORD;
  CREATE TABLE "TR_LTM_SLS_RTN_ORD" 
   (	
   "ID_ORD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE , 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_ORD_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"DC_ORD_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ST_ITM_ORD" NUMBER(*,0), 
	"ST_PREV_ITM" NUMBER(*,0), 
	"NBTY_ATG_ORD_ID" VARCHAR2(20 BYTE)
   );
 

   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."ID_ORD" IS 'OrderID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."DC_DY_BSN" IS 'BuisnessDay';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."AI_TRN" IS 'TransactionID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."AI_ORD_LN_ITM" IS 'OrderLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."DC_ORD_DY_BSN" IS 'OrderBuisnessDay';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."ST_ITM_ORD" IS 'OrderLineItemStatus';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."ST_PREV_ITM" IS 'OrderLineItemPreviousStatus';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_ORD"."NBTY_ATG_ORD_ID" IS 'ATG Order ID';
 
   COMMENT ON TABLE "TR_LTM_SLS_RTN_ORD"  IS 'OrderLineItemStatus';
 
   ALTER TABLE "TR_LTM_SLS_RTN_ORD" ADD PRIMARY KEY ("ID_ORD", "ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM", "AI_ORD_LN_ITM", "DC_ORD_DY_BSN");


--------------------------------------------------------
--  DDL for Table TR_LTM_SLS_RTN_TX
--------------------------------------------------------
  DROP TABLE TR_LTM_SLS_RTN_TX;
  CREATE TABLE "TR_LTM_SLS_RTN_TX" 
   (	"ID_STR_RT" VARCHAR2(5 BYTE)  NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ATHY_TX" NUMBER(*,0) DEFAULT 0, 
	"ID_GP_TX" NUMBER(*,0) DEFAULT 0, 
	"TY_TX" NUMBER(*,0) DEFAULT 0, 
	"FLG_TX_HDY" CHAR(1 BYTE) DEFAULT '0', 
	"TX_MOD" NUMBER(*,0) DEFAULT 0, 
	"MO_TXBL_RTN_SLS" NUMBER(16,5) DEFAULT 0, 
	"MO_TX_RTN_SLS" NUMBER(16,5) DEFAULT 0, 
	"MO_TX_RTN_SLS_TOT" NUMBER(16,5) DEFAULT 0, 
	"NM_RU_TX" VARCHAR2(120 BYTE) DEFAULT 'LOCAL TAX', 
	"PE_TX" NUMBER(8,5) DEFAULT 8.25, 
	"ID_UNQ" VARCHAR2(35 BYTE) DEFAULT '1001-0-0', 
	"FL_TX_INC" CHAR(1 BYTE) DEFAULT '0', 
	"MO_TX_INC_RTN_SLS_TOT" NUMBER(16,5) DEFAULT 0, 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."ID_ATHY_TX" IS 'TaxAuthorityID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."ID_GP_TX" IS 'TaxGroupID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."TY_TX" IS 'TaxType';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."FLG_TX_HDY" IS 'TaxHolidayFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."TX_MOD" IS 'TaxMode';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."MO_TXBL_RTN_SLS" IS 'TaxableAmount';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."MO_TX_RTN_SLS" IS 'TaxAmountPerAuthority';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."MO_TX_RTN_SLS_TOT" IS 'TaxAmountTotal';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."NM_RU_TX" IS 'TaxRuleName';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."PE_TX" IS 'TaxPercentage';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."ID_UNQ" IS 'UniqueAuthorityGroupTypeTaxID';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."FL_TX_INC" IS 'InclusiveTaxFlag';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."MO_TX_INC_RTN_SLS_TOT" IS 'InclusiveTaxAmountTotal';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_SLS_RTN_TX"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "TR_LTM_SLS_RTN_TX"  IS 'SaleReturnTaxLineItem';

   ALTER TABLE "TR_LTM_SLS_RTN_TX" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM", "ID_ATHY_TX", "ID_GP_TX", "TY_TX");
   
   
   --------------------------------------------------------
--  DDL for Table TR_LTM_TX
--------------------------------------------------------
  DROP TABLE TR_LTM_TX;
  CREATE TABLE "TR_LTM_TX" 
   (	"ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_GP_TX" NUMBER(*,0) DEFAULT 0, 
	"ID_ATHY_TX" NUMBER(*,0) DEFAULT 0, 
	"MO_TX" NUMBER(13,2) DEFAULT 0, 
	"RC_TX" VARCHAR2(20 BYTE), 
	"TY_TX" NUMBER(*,0) DEFAULT 0, 
	"PE_TX" NUMBER(8,5) DEFAULT 0, 
	"PE_TX_OVRD" NUMBER(8,5) DEFAULT 0, 
	"MO_TX_OVRD" NUMBER(13,2) DEFAULT 0, 
	"MO_TX_INC" NUMBER(13,2) DEFAULT 0, 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "TR_LTM_TX"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_TX"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_TX"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_TX"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_TX"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_TX"."ID_GP_TX" IS 'TaxGroupID';
 
   COMMENT ON COLUMN "TR_LTM_TX"."ID_ATHY_TX" IS 'TaxAuthorityID';
 
   COMMENT ON COLUMN "TR_LTM_TX"."MO_TX" IS 'TaxAmount';
 
   COMMENT ON COLUMN "TR_LTM_TX"."RC_TX" IS 'TaxReasonCode';
 
   COMMENT ON COLUMN "TR_LTM_TX"."TY_TX" IS 'TaxTypeCode';
 
   COMMENT ON COLUMN "TR_LTM_TX"."PE_TX" IS 'TaxPercent';
 
   COMMENT ON COLUMN "TR_LTM_TX"."PE_TX_OVRD" IS 'TaxOverridePercent';
 
   COMMENT ON COLUMN "TR_LTM_TX"."MO_TX_OVRD" IS 'TaxOverrideAmount';
 
   COMMENT ON COLUMN "TR_LTM_TX"."MO_TX_INC" IS 'InclusiveTaxAmount';
 
   COMMENT ON COLUMN "TR_LTM_TX"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_TX"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "TR_LTM_TX"  IS 'TaxLineItem';

   ALTER TABLE "TR_LTM_TX" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");
   
   
   
--------------------------------------------------------
--  DDL for Table TR_LTM_TND
--------------------------------------------------------
  DROP TABLE TR_LTM_TND;
  CREATE TABLE "TR_LTM_TND" 
   (	"ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"TY_TND" VARCHAR2(20 BYTE), 
	"ID_ACNT_NMB" NUMBER(*,0) DEFAULT 0, 
	"ID_ACNT_TND" NUMBER(*,0) DEFAULT 0, 
	"MO_ITM_LN_TND" NUMBER(13,2) DEFAULT 0, 
	"ID_CNY_ICD" NUMBER(*,0), 
	"LCL_DE_CNY" VARCHAR2(250 BYTE), 
	"DE_FRG_CNY" VARCHAR2(250 BYTE), 
	"MO_RT_TO_BUY" NUMBER(13,6) DEFAULT 0, 
	"CO_CNCT_FRG_CNY" VARCHAR2(3 BYTE), 
	"FRG_MO_ITM_LN_TND" NUMBER(13,2) DEFAULT 0, 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9), 
	"RND_AMT" NUMBER(13,2), 
	"REFERENCE_ID" VARCHAR2(100 BYTE)
   );
 
   ALTER TABLE "TR_LTM_TND" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");


--------------------------------------------------------
--  DDL for Table TR_LTM_CR_STR_TND
--------------------------------------------------------
  DROP TABLE TR_LTM_CR_STR_TND;
  CREATE TABLE "TR_LTM_CR_STR_TND" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_STR_ISSG" VARCHAR2(5 BYTE), 
	"ID_CR_STR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MO_CR_STR" NUMBER(13,2) NOT NULL ENABLE, 
	"SC_CR_STR_TND" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"MO_VL_FC_SC_CR_CF" NUMBER(13,2) NOT NULL ENABLE, 
	"ID_CNY_ICD" NUMBER(*,0), 
	"FN_PRS_CR_STR" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"LN_PRS_CR_STR" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"TY_ID_CR_STR" VARCHAR2(40 BYTE) NOT NULL ENABLE
   );
 

   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."ID_STR_ISSG" IS 'IssuingStoreID';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."ID_CR_STR" IS 'StoreCreditID';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."MO_CR_STR" IS 'StoreCreditAmount';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."SC_CR_STR_TND" IS 'StoreCreditStatusCode';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."MO_VL_FC_SC_CR_CF" IS 'StoreCreditForeignAmount';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."ID_CNY_ICD" IS 'CurrencyID';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."FN_PRS_CR_STR" IS 'FirstName';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."LN_PRS_CR_STR" IS 'LastName';
 
   COMMENT ON COLUMN "TR_LTM_CR_STR_TND"."TY_ID_CR_STR" IS 'IdType';
 
   COMMENT ON TABLE "TR_LTM_CR_STR_TND"  IS 'StoreCreditTenderLineItem';
  
   ALTER TABLE "TR_LTM_CR_STR_TND" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");

--------------------------------------------------------
--  DDL for Table TR_LTM_GF_CF_TND
--------------------------------------------------------
  DROP TABLE TR_LTM_GF_CF_TND;
  CREATE TABLE "TR_LTM_GF_CF_TND" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_STR_ISSG" VARCHAR2(5 BYTE), 
	"ID_NMB_SRZ_GF_CF" VARCHAR2(40 BYTE), 
	"MO_VL_FC_GF_CF" NUMBER(10,2), 
	"MO_VL_FC_FRG_GF_CF" NUMBER(10,2), 
	"ID_CNY_ICD" NUMBER(*,0), 
	"TY_SB_GF_CF" VARCHAR2(20 BYTE)
   );
 

   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."ID_STR_ISSG" IS 'IssuingStoreID';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."ID_NMB_SRZ_GF_CF" IS 'GiftCertificateSerialNumber';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."MO_VL_FC_GF_CF" IS 'GiftCertificateFaceValueAmount';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."MO_VL_FC_FRG_GF_CF" IS 'GiftCertificateForeignFaceValueAmount';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."ID_CNY_ICD" IS 'CurrencyID';
 
   COMMENT ON COLUMN "TR_LTM_GF_CF_TND"."TY_SB_GF_CF" IS 'GiftCertificateSubType';
 
   COMMENT ON TABLE "TR_LTM_GF_CF_TND"  IS 'GiftCertificateTenderLineItem';
 
   ALTER TABLE "TR_LTM_GF_CF_TND" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");

   
--------------------------------------------------------
--  DDL for Table TR_LTM_CRDB_CRD_TN
--------------------------------------------------------
  DROP TABLE TR_LTM_CRDB_CRD_TN;
  CREATE TABLE "TR_LTM_CRDB_CRD_TN" 
   (	
   "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"TY_TND" VARCHAR2(20 BYTE), 
	"ID_ISSR_TND_MD" VARCHAR2(250 BYTE), 
	"TY_CRD" VARCHAR2(40 BYTE), 
	"TY_ID_PRSL_RQ" VARCHAR2(20 BYTE), 
	"ID_RFC_PRSL_ID" VARCHAR2(20 BYTE), 
	"LU_MTH_AZN" VARCHAR2(20 BYTE), 
	"LU_AJD_CR_DB" VARCHAR2(40 BYTE), 
	"LU_NMB_CRD_SWP_KY" VARCHAR2(20 BYTE), 
	"CH_IM_TND_AZN_CT" BLOB, 
	"TY_ID" VARCHAR2(20 BYTE), 
	"CNTRY_ID" VARCHAR2(3 BYTE), 
	"ST_ID" VARCHAR2(3 BYTE), 
	"DC_EP_DB_ID" TIMESTAMP (9), 
	"LU_ACNT_CRD_TKN" VARCHAR2(100 BYTE), 
	"ID_MSK_ACNT_CRD" VARCHAR2(20 BYTE), 
	"LU_AZN_STLM_DT" VARCHAR2(16 BYTE), 
	"TS_AZN" TIMESTAMP (9), 
	"AI_MSG_AZN" VARCHAR2(5 BYTE), 
	"DC_AZN_CRD" VARCHAR2(10 BYTE), 
	"TM_AZN_CRD" VARCHAR2(10 BYTE), 
	"ID_RTRVD_REF" VARCHAR2(20 BYTE), 
	"CD_RSPS" VARCHAR2(20 BYTE), 
	"CD_AZN_DT_ACNT_SRC_ORGL" VARCHAR2(10 BYTE), 
	"FL_AZN_PYM_SV_ORGL" CHAR(1 BYTE), 
	"ID_AZN_TRN_ORGL" VARCHAR2(20 BYTE), 
	"CD_AZN_VLD_ORGL" VARCHAR2(10 BYTE), 
	"CD_AZN_SRC_ORGL" VARCHAR2(10 BYTE), 
	"ID_REF_TRN_HOST_ORGL" VARCHAR2(250 BYTE), 
	"ID_TRC_TRN" VARCHAR2(20 BYTE), 
	"MO_BLNC_PPD_RMN" NUMBER(13,2), 
	"ID_NMB_SRZ_KY" VARCHAR2(20 BYTE), 
	"LV_ACC_AFT_PRM_APR" VARCHAR2(8 BYTE), 
	"TY_ACC_AFT_PRM_APR" VARCHAR2(1 BYTE), 
	"LV_DRNG_PRM_APR" VARCHAR2(8 BYTE), 
	"TY_DRNG_PRM_APR" VARCHAR2(1 BYTE), 
	"DE_PRM" VARCHAR2(60 BYTE), 
	"DE_DRNG_PRM" VARCHAR2(40 BYTE), 
	"LU_AZN_JL_KY" VARCHAR2(25 BYTE), 
	"ACNT_CRD_TKN_ORGN" VARCHAR2(10 BYTE), 
	"TY_PAY_TRN" VARCHAR2(10 BYTE)
   );
 

   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."DC_DY_BSN" IS 'BusinessDayDate';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."TY_TND" IS 'TenderTypeCode';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_ISSR_TND_MD" IS 'TenderMediaIssuerID';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."TY_CRD" IS 'CardType';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."TY_ID_PRSL_RQ" IS 'PersonalIDRequiredType';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_RFC_PRSL_ID" IS 'PersonalIDReferenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."LU_MTH_AZN" IS 'AuthorizationMethodCode';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."LU_AJD_CR_DB" IS 'CreditDebitCardAdjudicationCode';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."LU_NMB_CRD_SWP_KY" IS 'CardNumberSwipedOrKeyedCode';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."CH_IM_TND_AZN_CT" IS 'CustomerSignatureImage';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."TY_ID" IS 'IDType';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."CNTRY_ID" IS 'IDCountry';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ST_ID" IS 'IDState';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."DC_EP_DB_ID" IS 'IDExpirationDate';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."LU_ACNT_CRD_TKN" IS 'AccountNumberToken';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_MSK_ACNT_CRD" IS 'MaskedAccountNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."LU_AZN_STLM_DT" IS 'AuthorizationSettlementData';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."TS_AZN" IS 'AuthorizationTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."AI_MSG_AZN" IS 'AuthorizationMessageSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."DC_AZN_CRD" IS 'AuthorizationDate';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."TM_AZN_CRD" IS 'AuthorizationTime';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_RTRVD_REF" IS 'RetrivalReferenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."CD_RSPS" IS 'ResponseCode';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."CD_AZN_DT_ACNT_SRC_ORGL" IS 'OriginalAuthorizationAccountDataSourceCode';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."FL_AZN_PYM_SV_ORGL" IS 'OriginalAuthorizationPaymentServiceIndicator';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_AZN_TRN_ORGL" IS 'OriginalAuthorizationTransactionIdentificationNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."CD_AZN_VLD_ORGL" IS 'OriginalAuthorizationValidationCode';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."CD_AZN_SRC_ORGL" IS 'OriginalAuthorizationSourceCode';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_REF_TRN_HOST_ORGL" IS 'OriginalHostTransactionReferenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_TRC_TRN" IS 'TransactionTraceNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."MO_BLNC_PPD_RMN" IS 'RemainingPrepaidBalanceAmount';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."ID_NMB_SRZ_KY" IS 'KeySerialNumber';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."LV_ACC_AFT_PRM_APR" IS 'AccountAfterPromotionAPR';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."TY_ACC_AFT_PRM_APR" IS 'AccountAfterPromotionAPRType';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."LV_DRNG_PRM_APR" IS 'DuringPromotionAPR';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."TY_DRNG_PRM_APR" IS 'DuringPromotionAPRType';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."DE_PRM" IS 'PromotionDescription';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."DE_DRNG_PRM" IS 'PromotionDuration';
 
   COMMENT ON COLUMN "TR_LTM_CRDB_CRD_TN"."LU_AZN_JL_KY" IS 'AuthorizationJournalKey';
 
   COMMENT ON TABLE "TR_LTM_CRDB_CRD_TN"  IS 'CreditDebitCardTenderLineItem';

   ALTER TABLE "TR_LTM_CRDB_CRD_TN" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");


 
--------------------------------------------------------
--  DDL for Table OR_ORD
--------------------------------------------------------
  DROP TABLE OR_ORD;
  CREATE TABLE "OR_ORD" 
   (	
    "ID_ORD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ID_CT" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ST_ORD" NUMBER(*,0) DEFAULT -1, 
	"ST_PREV_ORD" NUMBER(*,0) DEFAULT -1, 
	"FL_TRG_TRN" CHAR(1 BYTE) DEFAULT '0', 
	"NM_LCN_STR" VARCHAR2(60 BYTE), 
	"ID_STR_RT" VARCHAR2(5 BYTE), 
	"DC_DY_BSN_CHG" VARCHAR2(10 BYTE), 
	"ID_REGISTRY" VARCHAR2(14 BYTE), 
	"DC_DY_BSN_BGN" VARCHAR2(30 BYTE), 
	"ID_OPR" VARCHAR2(10 BYTE), 
	"DESC_ORD" VARCHAR2(250 BYTE), 
	"TOT_ORD" NUMBER(13,2) DEFAULT 0, 
	"LN_CNCT" VARCHAR2(120 BYTE), 
	"FN_CNCT" VARCHAR2(120 BYTE), 
	"MD_CNCT" VARCHAR2(120 BYTE), 
	"EM_ADS" VARCHAR2(64 BYTE), 
	"MO_ORD_DS" NUMBER(13,2) DEFAULT 0, 
	"MO_ORD_DS_MNM" NUMBER(13,2) DEFAULT 0, 
	"MO_BLNC_ORD" NUMBER(13,2) DEFAULT 0, 
	"CHL_ORD_CRT" CHAR(1 BYTE) DEFAULT '0', 
	"ID_STR_RT_ORGL" VARCHAR2(5 BYTE), 
	"ID_WS_ORGL" VARCHAR2(3 BYTE), 
	"DC_DY_BSN_ORGL" VARCHAR2(10 BYTE), 
	"AI_TRN_ORGL" NUMBER(*,0), 
	"ID_STR_RT_RCRD" VARCHAR2(5 BYTE), 
	"ID_WS_RCRD" VARCHAR2(3 BYTE), 
	"DC_DY_BSN_RCRD" VARCHAR2(10 BYTE), 
	"AI_TRN_RCRD" NUMBER(*,0), 
	"TY_ORD" NUMBER(*,0), 
	"MO_ORD_SLS" NUMBER(13,2) DEFAULT 0, 
	"TS_BGN_ORD" TIMESTAMP (9), 
	"TS_CRT_ORD" TIMESTAMP (9), 
	"TS_MDF_ORD" TIMESTAMP (9), 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9), 
	"NBTY_NOTIF_PREF" VARCHAR2(20 BYTE), 
	"FLG_BO" NUMBER(13,2) DEFAULT 0, 
	"FLG_OIS" CHAR(1 BYTE), 
	"NBTY_ATG_ORD_ID" VARCHAR2(20 BYTE)
   );
 

   COMMENT ON COLUMN "OR_ORD"."ID_ORD" IS 'OrderID';
 
   COMMENT ON COLUMN "OR_ORD"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "OR_ORD"."ID_CT" IS 'CustomerID';
 
   COMMENT ON COLUMN "OR_ORD"."ST_ORD" IS 'OrderStatus';
 
   COMMENT ON COLUMN "OR_ORD"."ST_PREV_ORD" IS 'OrderStatusPrevious';
 
   COMMENT ON COLUMN "OR_ORD"."FL_TRG_TRN" IS 'TransactionTrainingFlag';
 
   COMMENT ON COLUMN "OR_ORD"."NM_LCN_STR" IS 'OrderLocation';
 
   COMMENT ON COLUMN "OR_ORD"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "OR_ORD"."DC_DY_BSN_CHG" IS 'OrderStatusChange';
 
   COMMENT ON COLUMN "OR_ORD"."ID_REGISTRY" IS 'GiftRegistryID';
 
   COMMENT ON COLUMN "OR_ORD"."DC_DY_BSN_BGN" IS 'OrderBegin';
 
   COMMENT ON COLUMN "OR_ORD"."ID_OPR" IS 'OperatorID';
 
   COMMENT ON COLUMN "OR_ORD"."DESC_ORD" IS 'OrderDescription';
 
   COMMENT ON COLUMN "OR_ORD"."TOT_ORD" IS 'OrderTotal';
 
   COMMENT ON COLUMN "OR_ORD"."LN_CNCT" IS 'ContactLastName';
 
   COMMENT ON COLUMN "OR_ORD"."FN_CNCT" IS 'ContactFirstName';
 
   COMMENT ON COLUMN "OR_ORD"."MD_CNCT" IS 'ContactMiddleInitial';
 
   COMMENT ON COLUMN "OR_ORD"."EM_ADS" IS 'EmailAddress';
 
   COMMENT ON COLUMN "OR_ORD"."MO_ORD_DS" IS 'OrderDepositAmount';
 
   COMMENT ON COLUMN "OR_ORD"."MO_ORD_DS_MNM" IS 'OrderDepositMinimumAmount';
 
   COMMENT ON COLUMN "OR_ORD"."MO_BLNC_ORD" IS 'OrderBalance';
 
   COMMENT ON COLUMN "OR_ORD"."CHL_ORD_CRT" IS 'OrderInitiationChannel';
 
   COMMENT ON COLUMN "OR_ORD"."ID_STR_RT_ORGL" IS 'OriginalTransactionRetailStoreID';
 
   COMMENT ON COLUMN "OR_ORD"."ID_WS_ORGL" IS 'OriginalTransactionWorkstationID';
 
   COMMENT ON COLUMN "OR_ORD"."DC_DY_BSN_ORGL" IS 'OriginalTransactionBusinessDate';
 
   COMMENT ON COLUMN "OR_ORD"."AI_TRN_ORGL" IS 'OriginalTransactionSequenceNumber';
 
   COMMENT ON COLUMN "OR_ORD"."ID_STR_RT_RCRD" IS 'RecordingTransactionRetailStoreID';
 
   COMMENT ON COLUMN "OR_ORD"."ID_WS_RCRD" IS 'RecordingTransactionWorkstationID';
 
   COMMENT ON COLUMN "OR_ORD"."DC_DY_BSN_RCRD" IS 'RecordingTransactionBusinessDate';
 
   COMMENT ON COLUMN "OR_ORD"."AI_TRN_RCRD" IS 'RecordingTransactionSequenceNumber';
 
   COMMENT ON COLUMN "OR_ORD"."TY_ORD" IS 'OrderType';
 
   COMMENT ON COLUMN "OR_ORD"."MO_ORD_SLS" IS 'OrderSalesDeposit';
 
   COMMENT ON COLUMN "OR_ORD"."TS_BGN_ORD" IS 'OrderBeginTimestamp';
 
   COMMENT ON COLUMN "OR_ORD"."TS_CRT_ORD" IS 'OrderCreationTimestamp';
 
   COMMENT ON COLUMN "OR_ORD"."TS_MDF_ORD" IS 'OrderLastModifiedTimestamp';
 
   COMMENT ON COLUMN "OR_ORD"."TS_CRT_RCRD" IS 'RecordCreationTimestamp';
 
   COMMENT ON COLUMN "OR_ORD"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON COLUMN "OR_ORD"."NBTY_NOTIF_PREF" IS 'NotificationPreference';
 
   COMMENT ON COLUMN "OR_ORD"."FLG_BO" IS 'BOFlag';
 
   COMMENT ON COLUMN "OR_ORD"."FLG_OIS" IS 'OrderInStoreFlag';
 
   COMMENT ON COLUMN "OR_ORD"."NBTY_ATG_ORD_ID" IS 'ATG Order ID';
 
   COMMENT ON TABLE "OR_ORD"  IS 'Order';

   ALTER TABLE "OR_ORD" ADD PRIMARY KEY ("ID_ORD", "DC_DY_BSN");


--------------------------------------------------------
--  DDL for Table OR_LTM
--------------------------------------------------------
  DROP TABLE OR_LTM;
  CREATE TABLE "OR_LTM" 
   (	
    "ID_ORD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"QU_ITM_PCK" NUMBER(9,2) DEFAULT 0, 
	"QU_ITM_SHP" NUMBER(9,2) DEFAULT 0, 
	"ST_ITM_ORD" NUMBER(*,0) DEFAULT -1, 
	"ST_PREV_ITM" NUMBER(*,0) DEFAULT -1, 
	"DC_DY_BSN_CHG" VARCHAR2(10 BYTE), 
	"LN_ITM_REF" NUMBER(*,0) DEFAULT 0, 
	"ID_STR_RT" VARCHAR2(5 BYTE), 
	"ID_WS" VARCHAR2(3 BYTE), 
	"AI_TRN" NUMBER(*,0) DEFAULT -1, 
	"ID_PRTY" NUMBER(*,0) DEFAULT 0, 
	"ID_REGISTRY" VARCHAR2(14 BYTE), 
	"ID_GP_TX" NUMBER(*,0) DEFAULT 0, 
	"ID_DPT_POS" VARCHAR2(14 BYTE), 
	"ID_ITM_POS" VARCHAR2(14 BYTE), 
	"ID_ITM" VARCHAR2(14 BYTE), 
	"QU_ITM_LM_RTN_SLS" NUMBER(9,2) DEFAULT 0, 
	"MO_EXTN_LN_ITM_RTN" NUMBER(13,2) DEFAULT 0, 
	"MO_VAT_LN_ITM_RTN" NUMBER(13,2) DEFAULT 0, 
	"DE_ITM" VARCHAR2(250 BYTE), 
	"TY_TX" NUMBER(*,0) DEFAULT 0, 
	"FL_RTN_MR" CHAR(1 BYTE), 
	"RC_RTN_MR" VARCHAR2(2 BYTE), 
	"FL_RFD_SV" CHAR(1 BYTE), 
	"RC_RFD_SV" VARCHAR2(2 BYTE), 
	"LU_MTH_ID_ENR" VARCHAR2(4 BYTE), 
	"LU_ENTR_RT_PRC" VARCHAR2(4 BYTE), 
	"LU_PRC_RT_DRVN" VARCHAR2(4 BYTE), 
	"NM_RTN_FM" VARCHAR2(120 BYTE), 
	"CC_RTN_FM" VARCHAR2(3 BYTE), 
	"TA_RTN_FM" VARCHAR2(5 BYTE), 
	"TL_RTN_FM" VARCHAR2(30 BYTE), 
	"A1_ADS_RTN_FM" VARCHAR2(240 BYTE), 
	"A2_ADS_RTN_FM" VARCHAR2(240 BYTE), 
	"CI_ADS_RTN_FM" VARCHAR2(120 BYTE), 
	"ST_ADS_RTN_FM" VARCHAR2(2 BYTE), 
	"PC_ADS_RTN_FM" VARCHAR2(20 BYTE), 
	"MO_ORD_DS" NUMBER(13,2) DEFAULT 0, 
	"MO_TAX_INC_LN_ITM_RTN" NUMBER(13,2) DEFAULT 0, 
	"DC_ORD_PCKP" DATE, 
	"AI_ORD_DEL_DTL" NUMBER(*,0), 
	"AI_ORD_RCPNT" NUMBER(*,0), 
	"DP_ORD_LN_ITM" VARCHAR2(4 BYTE) DEFAULT '1'
   );
 

   COMMENT ON COLUMN "OR_LTM"."ID_ORD" IS 'OrderID';
 
   COMMENT ON COLUMN "OR_LTM"."AI_LN_ITM" IS 'LineItemSequenceNumber';
 
   COMMENT ON COLUMN "OR_LTM"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "OR_LTM"."QU_ITM_PCK" IS 'ItemQuantityPicked';
 
   COMMENT ON COLUMN "OR_LTM"."QU_ITM_SHP" IS 'ItemQuantityShipped';
 
   COMMENT ON COLUMN "OR_LTM"."ST_ITM_ORD" IS 'ItemStatus';
 
   COMMENT ON COLUMN "OR_LTM"."ST_PREV_ITM" IS 'ItemStatusPrevious';
 
   COMMENT ON COLUMN "OR_LTM"."DC_DY_BSN_CHG" IS 'OrderStatusChange';
 
   COMMENT ON COLUMN "OR_LTM"."LN_ITM_REF" IS 'LineItemReferenceNumber';
 
   COMMENT ON COLUMN "OR_LTM"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "OR_LTM"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "OR_LTM"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "OR_LTM"."ID_PRTY" IS 'PartyID';
 
   COMMENT ON COLUMN "OR_LTM"."ID_REGISTRY" IS 'GiftRegistryID';
 
   COMMENT ON COLUMN "OR_LTM"."ID_GP_TX" IS 'TaxGroupID';
 
   COMMENT ON COLUMN "OR_LTM"."ID_DPT_POS" IS 'POSDepartmentID';
 
   COMMENT ON COLUMN "OR_LTM"."ID_ITM_POS" IS 'POSItemID';
 
   COMMENT ON COLUMN "OR_LTM"."ID_ITM" IS 'ItemID';
 
   COMMENT ON COLUMN "OR_LTM"."QU_ITM_LM_RTN_SLS" IS 'SaleReturnLineItemQuantity';
 
   COMMENT ON COLUMN "OR_LTM"."MO_EXTN_LN_ITM_RTN" IS 'SaleReturnLineItemExtendedAmount';
 
   COMMENT ON COLUMN "OR_LTM"."MO_VAT_LN_ITM_RTN" IS 'SaleReturnLineItemVatAmount';
 
   COMMENT ON COLUMN "OR_LTM"."DE_ITM" IS 'ItemDescription';
 
   COMMENT ON COLUMN "OR_LTM"."TY_TX" IS 'TaxTypeCode';
 
   COMMENT ON COLUMN "OR_LTM"."FL_RTN_MR" IS 'MerchandiseReturnFlag';
 
   COMMENT ON COLUMN "OR_LTM"."RC_RTN_MR" IS 'MerchandiseReturnReasonCode';
 
   COMMENT ON COLUMN "OR_LTM"."FL_RFD_SV" IS 'ServiceRefundFlag';
 
   COMMENT ON COLUMN "OR_LTM"."RC_RFD_SV" IS 'ServiceRefundReasonCode';
 
   COMMENT ON COLUMN "OR_LTM"."LU_MTH_ID_ENR" IS 'ItemIdEntryMethodCode';
 
   COMMENT ON COLUMN "OR_LTM"."LU_ENTR_RT_PRC" IS 'ItemSellUnitRetailPriceEntryMethodCode';
 
   COMMENT ON COLUMN "OR_LTM"."LU_PRC_RT_DRVN" IS 'ItemSellUnitRetailPriceDerivationMethodCode';
 
   COMMENT ON COLUMN "OR_LTM"."NM_RTN_FM" IS 'ReturnFormName';
 
   COMMENT ON COLUMN "OR_LTM"."CC_RTN_FM" IS 'ReturnFormPhoneCountryCode';
 
   COMMENT ON COLUMN "OR_LTM"."TA_RTN_FM" IS '@Deprecated(since 13.1)=ReturnFormPhoneAreaCode';
 
   COMMENT ON COLUMN "OR_LTM"."TL_RTN_FM" IS 'ReturnFormPhoneNumber';
 
   COMMENT ON COLUMN "OR_LTM"."A1_ADS_RTN_FM" IS 'ReturnFormAddressLine1';
 
   COMMENT ON COLUMN "OR_LTM"."A2_ADS_RTN_FM" IS 'ReturnFormAddressLine2';
 
   COMMENT ON COLUMN "OR_LTM"."CI_ADS_RTN_FM" IS 'ReturnFormAddressCity';
 
   COMMENT ON COLUMN "OR_LTM"."ST_ADS_RTN_FM" IS 'ReturnFormAddressState';
 
   COMMENT ON COLUMN "OR_LTM"."PC_ADS_RTN_FM" IS 'ReturnFormAddressPostalCode';
 
   COMMENT ON COLUMN "OR_LTM"."MO_ORD_DS" IS 'DepositAmount';
 
   COMMENT ON COLUMN "OR_LTM"."MO_TAX_INC_LN_ITM_RTN" IS 'OrderLineItemInclusiveTaxAmount';
 
   COMMENT ON COLUMN "OR_LTM"."DC_ORD_PCKP" IS 'OrderPickupDate';
 
   COMMENT ON COLUMN "OR_LTM"."AI_ORD_DEL_DTL" IS 'OrderDeliverySequenceNumber';
 
   COMMENT ON COLUMN "OR_LTM"."AI_ORD_RCPNT" IS 'OrderRecipientSequenceNumber';
 
   COMMENT ON COLUMN "OR_LTM"."DP_ORD_LN_ITM" IS 'OrderLineItemDespositionCode';
 
   COMMENT ON TABLE "OR_LTM"  IS 'OrderLineItem';

   ALTER TABLE "OR_LTM" ADD PRIMARY KEY ("ID_ORD", "AI_LN_ITM", "DC_DY_BSN");
   
   
   
   --------------------------------------------------------
--  DDL for Table CO_MDFR_RTL_PRC
--------------------------------------------------------
  DROP TABLE CO_MDFR_RTL_PRC;
  CREATE TABLE "CO_MDFR_RTL_PRC" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_MDFR_RT_PRC" NUMBER(*,0), 
	"RC_MDFR_RT_PRC" VARCHAR2(20 BYTE), 
	"PE_MDFR_RT_PRC" NUMBER(5,2) DEFAULT 0, 
	"MO_MDFR_RT_PRC" NUMBER(16,5) DEFAULT 0, 
	"DP_LDG_STK_MDFR" VARCHAR2(20 BYTE), 
	"ID_RU_MDFR" NUMBER(*,0) DEFAULT 1, 
	"CD_MTH_PRDV" NUMBER(*,0) DEFAULT 0, 
	"CD_BAS_PRDV" NUMBER(*,0) DEFAULT 0, 
	"CD_TY_PRDV" NUMBER(*,0) DEFAULT 0, 
	"FL_PCD_DL_ADVN_APLY" CHAR(1 BYTE) DEFAULT '0', 
	"FL_DSC_ADVN_PRC" CHAR(1 BYTE) DEFAULT '0', 
	"ID_DSC_REF" VARCHAR2(255 BYTE), 
	"CO_ID_DSC_REF" VARCHAR2(2 BYTE) DEFAULT 'UN', 
	"ID_EM_AZN_OVRD" VARCHAR2(10 BYTE), 
	"CD_MTH_ENR_OVRD" NUMBER(*,0) DEFAULT -1, 
	"ID_DSC_EM" VARCHAR2(10 BYTE), 
	"FL_DSC_DMG" CHAR(1 BYTE) DEFAULT '0', 
	"ID_PRM" NUMBER(*,0) DEFAULT 0, 
	"ID_PRM_CMP" NUMBER(*,0) DEFAULT 0, 
	"ID_PRM_CMP_DTL" NUMBER(*,0) DEFAULT 0, 
	"ID_PRCGP" NUMBER(*,0), 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."AI_MDFR_RT_PRC" IS 'RetailPriceModifierSequenceNumber';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."RC_MDFR_RT_PRC" IS 'ReasonCode';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."PE_MDFR_RT_PRC" IS 'Percent';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."MO_MDFR_RT_PRC" IS 'Amount';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."DP_LDG_STK_MDFR" IS 'StockLedgerAccountingDispositionCode';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_RU_MDFR" IS 'DerivationRuleID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."CD_MTH_PRDV" IS 'MethodCode';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."CD_BAS_PRDV" IS 'AssignmentBasis';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."CD_TY_PRDV" IS 'TypeCode';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."FL_PCD_DL_ADVN_APLY" IS 'PCDAdvancedDealAppliedFlag';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."FL_DSC_ADVN_PRC" IS 'AdvancedPricingDiscountFlag';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_DSC_REF" IS 'DiscountReferenceID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."CO_ID_DSC_REF" IS 'DiscountReferenceTypeCode';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_EM_AZN_OVRD" IS 'OverrideAuthorizingEmployeeID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."CD_MTH_ENR_OVRD" IS 'OverrideEntryMethodCode';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_DSC_EM" IS 'EmployeeDiscountEmployeeID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."FL_DSC_DMG" IS 'DamageDiscountFlag';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_PRM" IS 'PromotionID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_PRM_CMP" IS 'PromotionComponentID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_PRM_CMP_DTL" IS 'PromotionComponentDetailID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."ID_PRCGP" IS 'CustomerPricingGroupID';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "CO_MDFR_RTL_PRC"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "CO_MDFR_RTL_PRC"  IS 'RetailPriceModifier';
 

 
  ALTER TABLE "CO_MDFR_RTL_PRC" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM", "AI_MDFR_RT_PRC");

  
  --------------------------------------------------------
--  DDL for Table CO_MDFR_SLS_RTN_TX
--------------------------------------------------------
  DROP TABLE CO_MDFR_SLS_RTN_TX;
  CREATE TABLE "CO_MDFR_SLS_RTN_TX" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_MDFR_TX" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_GP_TX" NUMBER(*,0) DEFAULT 0, 
	"ID_ATHY_TX" NUMBER(*,0) DEFAULT 0, 
	"MO_TX_RTN_SLS" NUMBER(16,5) DEFAULT 0, 
	"MO_TX_EXM_RTN_SLS" NUMBER(13,2) DEFAULT 0, 
	"RC_TX_EXM_RTN_SLS" VARCHAR2(20 BYTE), 
	"TY_TX" NUMBER(*,0) DEFAULT 0, 
	"PE_TX" NUMBER(8,5) DEFAULT 0, 
	"PE_TX_OVRD" NUMBER(8,5) DEFAULT 0, 
	"MO_TX_OVRD" NUMBER(13,2) DEFAULT 0, 
	"ID_SCP_TX" NUMBER(*,0) DEFAULT 0, 
	"ID_MTHD_TX" NUMBER(*,0) DEFAULT 0, 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."AI_MDFR_TX" IS 'TaxModifierSequenceNumber';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."ID_GP_TX" IS 'TaxGroupId';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."ID_ATHY_TX" IS 'TaxAuthorityId';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."MO_TX_RTN_SLS" IS 'SaleReturnTaxAmount';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."MO_TX_EXM_RTN_SLS" IS 'SaleReturnTaxExemptAmount';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."RC_TX_EXM_RTN_SLS" IS 'SaleReturnTaxExemptionReasonCode';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."TY_TX" IS 'TaxTypeCode';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."PE_TX" IS 'TaxPercent';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."PE_TX_OVRD" IS 'TaxOverridePercent';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."MO_TX_OVRD" IS 'TaxOverrideAmount';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."ID_SCP_TX" IS 'TaxScopeID';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."ID_MTHD_TX" IS 'TaxMethodID';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "CO_MDFR_SLS_RTN_TX"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "CO_MDFR_SLS_RTN_TX"  IS 'SaleReturnTaxModifier';

   ALTER TABLE "CO_MDFR_SLS_RTN_TX" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM", "AI_MDFR_TX");

  
  --------------------------------------------------------
--  DDL for Table TR_LTM_ORD_EXT
--------------------------------------------------------
  DROP TABLE TR_LTM_ORD_EXT;
  CREATE TABLE "TR_LTM_ORD_EXT" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_LTM_ORD_EXT" VARCHAR2(50 BYTE), 
	"ID_LTM_ORD_EXT_PRNT" VARCHAR2(250 BYTE), 
	"FL_EXT_PRC" CHAR(1 BYTE), 
	"FL_LTM_ORD_EXT_UPD_SRC" CHAR(1 BYTE)
   );
 

   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."AI_LN_ITM" IS 'LineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."ID_LTM_ORD_EXT" IS 'ExternalOrderLineItemID';
 
   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."ID_LTM_ORD_EXT_PRNT" IS 'ParentExternalOrderLineItemID';
 
   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."FL_EXT_PRC" IS 'ExternalPricingFlag';
 
   COMMENT ON COLUMN "TR_LTM_ORD_EXT"."FL_LTM_ORD_EXT_UPD_SRC" IS 'ExternalOrderLineItemSourceUpdateFlag';
 
   COMMENT ON TABLE "TR_LTM_ORD_EXT"  IS 'ExternalOrderLineItem';
 
   ALTER TABLE "TR_LTM_ORD_EXT" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");

  
  
  --------------------------------------------------------
--  DDL for Table TR_MDFR_SLS_RTN_PRC
--------------------------------------------------------
  DROP TABLE TR_MDFR_SLS_RTN_PRC;
  CREATE TABLE "TR_MDFR_SLS_RTN_PRC" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_MDFR_RT_PRC" NUMBER(*,0), 
	"RC_MDFR_RT_PRC" VARCHAR2(20 BYTE), 
	"PE_MDFR_RT_PRC" NUMBER(5,2) DEFAULT 0, 
	"MO_MDFR_RT_PRC" NUMBER(16,5) DEFAULT 0, 
	"DP_LDG_STK_MDFR" VARCHAR2(20 BYTE), 
	"ID_RU_MDFR" NUMBER(*,0) DEFAULT 1, 
	"CD_MTH_PRDV" NUMBER(*,0) DEFAULT 0, 
	"CD_BAS_PRDV" NUMBER(*,0) DEFAULT 0, 
	"CD_TY_PRDV" NUMBER(*,0) DEFAULT 0, 
	"FL_PCD_DL_ADVN_APLY" CHAR(1 BYTE) DEFAULT '0', 
	"FL_DSC_ADVN_PRC" CHAR(1 BYTE) DEFAULT '0', 
	"ID_DSC_REF" VARCHAR2(255 BYTE), 
	"CO_ID_DSC_REF" VARCHAR2(2 BYTE) DEFAULT 'UN', 
	"ID_EM_AZN_OVRD" VARCHAR2(10 BYTE), 
	"CD_MTH_ENR_OVRD" NUMBER(*,0) DEFAULT -1, 
	"ID_DSC_EM" VARCHAR2(10 BYTE), 
	"FL_DSC_DMG" CHAR(1 BYTE) DEFAULT '0', 
	"ID_PRM" NUMBER(*,0) DEFAULT 0, 
	"ID_PRM_CMP" NUMBER(*,0) DEFAULT 0, 
	"ID_PRM_CMP_DTL" NUMBER(*,0) DEFAULT 0, 
	"ID_PRCGP" NUMBER(*,0), 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."AI_MDFR_RT_PRC" IS 'RetailPriceModifierSequenceNumber';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."RC_MDFR_RT_PRC" IS 'ReasonCode';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."PE_MDFR_RT_PRC" IS 'Percent';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."MO_MDFR_RT_PRC" IS 'Amount';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."DP_LDG_STK_MDFR" IS 'StockLedgerAccountingDispositionCode';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_RU_MDFR" IS 'DerivationRuleID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."CD_MTH_PRDV" IS 'MethodCode';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."CD_BAS_PRDV" IS 'AssignmentBasis';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."CD_TY_PRDV" IS 'TypeCode';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."FL_PCD_DL_ADVN_APLY" IS 'PCDAdvancedDealAppliedFlag';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."FL_DSC_ADVN_PRC" IS 'AdvancedPricingDiscountFlag';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_DSC_REF" IS 'DiscountReferenceID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."CO_ID_DSC_REF" IS 'DiscountReferenceTypeCode';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_EM_AZN_OVRD" IS 'OverrideAuthorizingEmployeeID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."CD_MTH_ENR_OVRD" IS 'OverrideEntryMethodCode';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_DSC_EM" IS 'EmployeeDiscountEmployeeID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."FL_DSC_DMG" IS 'DamageDiscountFlag';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_PRM" IS 'PromotionID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_PRM_CMP" IS 'PromotionComponentID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_PRM_CMP_DTL" IS 'PromotionComponentDetailID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."ID_PRCGP" IS 'CustomerPricingGroupID';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "TR_MDFR_SLS_RTN_PRC"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "TR_MDFR_SLS_RTN_PRC"  IS 'SaleReturnPriceModifier';
 
   ALTER TABLE "TR_MDFR_SLS_RTN_PRC" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM", "AI_MDFR_RT_PRC");

   --------------------------------------------------------
--  DDL for Table TR_LTM_PRM
--------------------------------------------------------
  DROP TABLE TR_LTM_PRM;
  CREATE TABLE "TR_LTM_PRM" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LN_ITM" NUMBER(*,0) NOT NULL ENABLE, 
	"AI_LTM_PRM" NUMBER(*,0), 
	"ID_PRM" NUMBER(*,0) DEFAULT 0, 
	"ID_PRM_CMP" NUMBER(*,0) DEFAULT 0, 
	"ID_PRM_CMP_DTL" NUMBER(*,0) DEFAULT 0, 
	"ID_PRCGP" NUMBER(*,0), 
	"MO_MDFR_RT_PRC" NUMBER(16,5) DEFAULT 0, 
	"NM_EV_RCPT" VARCHAR2(120 BYTE) DEFAULT '', 
	"NM_EV_LCL" VARCHAR2(10 BYTE) DEFAULT 'en', 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "TR_LTM_PRM"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."AI_LN_ITM" IS 'RetailTransactionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."AI_LTM_PRM" IS 'PromotionLineItemSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."ID_PRM" IS 'PromotionID';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."ID_PRM_CMP" IS 'PromotionComponentID';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."ID_PRM_CMP_DTL" IS 'PromotionComponentDetailID';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."ID_PRCGP" IS 'CustomerPriceGroupID';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."MO_MDFR_RT_PRC" IS 'DiscountAmount';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."NM_EV_RCPT" IS 'PromotionNameUsedOnCustomerReceipt';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."NM_EV_LCL" IS 'PromotionNameLocale';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_PRM"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "TR_LTM_PRM"  IS 'PromotionLineItem';
  
   ALTER TABLE "TR_LTM_PRM" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "AI_LN_ITM");

--------------------------------------------------------
--  DDL for Table PA_CT
--------------------------------------------------------
  DROP TABLE PA_CT;
  CREATE TABLE "PA_CT" 
   (	
    "ID_CT" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ID_PRTY" NUMBER(*,0) NOT NULL ENABLE, 
	"NM_CT" VARCHAR2(250 BYTE), 
	"ID_EM" VARCHAR2(10 BYTE), 
	"STS_CT" NUMBER(*,0) DEFAULT 0, 
	"ID_NCRPT_ACTN_CRD" VARCHAR2(500 BYTE), 
	"ID_MSK_ACNT_CRD" VARCHAR2(20 BYTE), 
	"LCL" VARCHAR2(10 BYTE), 
	"ID_NCRPT_TAX" VARCHAR2(500 BYTE), 
	"ID_HSH_TAX" VARCHAR2(500 BYTE), 
	"ID_MSK_TAX" VARCHAR2(20 BYTE), 
	"ID_PRCGP" NUMBER(*,0), 
	"ID_CT_BTCH" NUMBER(*,0) DEFAULT -1, 
	"LTY_CUST_FLG" VARCHAR2(1 BYTE) DEFAULT '0', 
	"NBTY_PREF_LANG" VARCHAR2(10 BYTE)
   );
 

   COMMENT ON COLUMN "PA_CT"."ID_CT" IS 'CustomerID';
 
   COMMENT ON COLUMN "PA_CT"."ID_PRTY" IS 'PartyID';
 
   COMMENT ON COLUMN "PA_CT"."NM_CT" IS '@Mockable=CustomerName';
 
   COMMENT ON COLUMN "PA_CT"."ID_EM" IS 'EmployeeID';
 
   COMMENT ON COLUMN "PA_CT"."STS_CT" IS 'CustomerStatusCode';
 
   COMMENT ON COLUMN "PA_CT"."ID_NCRPT_ACTN_CRD" IS 'EncryptedAccountNumber';
 
   COMMENT ON COLUMN "PA_CT"."ID_MSK_ACNT_CRD" IS 'MaskedAccountNumber';
 
   COMMENT ON COLUMN "PA_CT"."LCL" IS '@Locale=CustomerPreferredLocale';
 
   COMMENT ON COLUMN "PA_CT"."ID_NCRPT_TAX" IS 'EncryptedCustomerTaxID';
 
   COMMENT ON COLUMN "PA_CT"."ID_HSH_TAX" IS 'HashedCustomerTaxID';
 
   COMMENT ON COLUMN "PA_CT"."ID_MSK_TAX" IS 'MaskedCustomerTaxID';
 
   COMMENT ON COLUMN "PA_CT"."ID_PRCGP" IS 'PricingGroupID';
 
   COMMENT ON COLUMN "PA_CT"."ID_CT_BTCH" IS 'CustomerBatchID';
 
   COMMENT ON COLUMN "PA_CT"."LTY_CUST_FLG" IS 'LoyaltyCustomerFlag';
 
   COMMENT ON COLUMN "PA_CT"."NBTY_PREF_LANG" IS 'Customer Preffered Language';
 
   COMMENT ON TABLE "PA_CT"  IS 'Customer';
 
   ALTER TABLE "PA_CT" ADD PRIMARY KEY ("ID_CT");

  --------------------------------------------------------
--  DDL for Table TR_LTM_PYAN
--------------------------------------------------------
  DROP TABLE TR_LTM_PYAN;
  CREATE TABLE "TR_LTM_PYAN" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_NCRPT_ACNT_CRD" VARCHAR2(500 BYTE), 
	"ID_MSK_ACNT_CRD" VARCHAR2(20 BYTE), 
	"ID_ACNT_NMB" VARCHAR2(20 BYTE), 
	"LU_ACNT_PYMAGT_RCV" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"MO_PYM_AGT_RCV" NUMBER(13,2) DEFAULT 0, 
	"MO_BLNC_ACNT" NUMBER(13,2) DEFAULT 0, 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "TR_LTM_PYAN"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."ID_NCRPT_ACNT_CRD" IS 'EncryptedCardAccountNumber';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."ID_MSK_ACNT_CRD" IS 'MaskedCardAccountNumber';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."ID_ACNT_NMB" IS 'AccountNumber';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."LU_ACNT_PYMAGT_RCV" IS 'PaymentAgainstReceivableCustomerAccountCode';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."MO_PYM_AGT_RCV" IS 'PaymentAgainstReceivableAmount';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."MO_BLNC_ACNT" IS 'BalanceDueAgainstAccount';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "TR_LTM_PYAN"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "TR_LTM_PYAN"  IS 'PaymentOnAccountLineItem';
 
   ALTER TABLE "TR_LTM_PYAN" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN"); 
   
   
   
--------------------------------------------------------
--  DDL for Table AS_WS
--------------------------------------------------------
  DROP TABLE AS_WS;
  CREATE TABLE "AS_WS" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE
   );
 

   COMMENT ON COLUMN "AS_WS"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "AS_WS"."AI_TRN" IS 'TransactionSequenceNumber';
 
   ALTER TABLE "AS_WS" ADD PRIMARY KEY ("ID_STR_RT");    
   
   
   
   
   --------------------------------------------------------
--  DDL for Table SHP_RDS_SLS_RTN
--------------------------------------------------------
  DROP TABLE SHP_RDS_SLS_RTN;
  CREATE TABLE "SHP_RDS_SLS_RTN" 
   (	
    "ID_STR_RT" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ID_WS" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DC_DY_BSN" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AI_TRN" NUMBER(*,0) NOT NULL ENABLE, 
	"CNT_SND_LAB" NUMBER(*,0) DEFAULT 0, 
	"FN_ADS_SLS_RTN" VARCHAR2(120 BYTE), 
	"LN_ADS_SLS_RTN" VARCHAR2(120 BYTE), 
	"NM_BSN" VARCHAR2(120 BYTE), 
	"FL_BSN_CT" CHAR(1 BYTE), 
	"A1_ADS_SLS_RTN" VARCHAR2(240 BYTE), 
	"A2_ADS_SLS_RTN" VARCHAR2(240 BYTE), 
	"CI_SLS_RTN" VARCHAR2(120 BYTE), 
	"ST_SLS_RTN" VARCHAR2(30 BYTE), 
	"PC_SLS_RTN" VARCHAR2(30 BYTE), 
	"EXTN_PC_SLS_RTN" VARCHAR2(15 BYTE), 
	"CO_SLS_RTN" VARCHAR2(30 BYTE), 
	"TY_PHN" VARCHAR2(30 BYTE), 
	"TA_CNCT" VARCHAR2(30 BYTE), 
	"TL_CNCT" VARCHAR2(30 BYTE), 
	"EXT_CNCT" VARCHAR2(30 BYTE), 
	"ID_SHP_MTH" NUMBER(*,0), 
	"SHP_CRR" VARCHAR2(120 BYTE), 
	"SHP_TYP" VARCHAR2(120 BYTE), 
	"SHP_BS_CHG" NUMBER(13,2) DEFAULT 0, 
	"SHP_CHG_RT_BY_WT" NUMBER(13,2) DEFAULT 0, 
	"FLT_RT" NUMBER(13,2) DEFAULT 0, 
	"SPL_INSTRC" VARCHAR2(2000 BYTE), 
	"SHP_CHG" NUMBER(13,2) DEFAULT 0, 
	"ID_GP_TX" NUMBER(*,0) DEFAULT 0, 
	"MO_TX" NUMBER(13,2) DEFAULT 0, 
	"MO_TX_INC" NUMBER(13,2) DEFAULT 0, 
	"FL_EXT_SHP" CHAR(1 BYTE) DEFAULT '0', 
	"TS_CRT_RCRD" TIMESTAMP (9), 
	"TS_MDF_RCRD" TIMESTAMP (9)
   );
 

   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."ID_STR_RT" IS 'RetailStoreID';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."ID_WS" IS 'WorkstationID';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."DC_DY_BSN" IS 'BusinessDay';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."AI_TRN" IS 'TransactionSequenceNumber';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."CNT_SND_LAB" IS 'SendLabelCount';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."FN_ADS_SLS_RTN" IS 'ShippingFirstName';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."LN_ADS_SLS_RTN" IS 'ShippingLastName';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."NM_BSN" IS 'BusinessName';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."FL_BSN_CT" IS 'BusinessCustomerFlag';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."A1_ADS_SLS_RTN" IS 'ShippingAddressLine1';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."A2_ADS_SLS_RTN" IS 'ShippingAddressLine2';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."CI_SLS_RTN" IS 'ShippingCity';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."ST_SLS_RTN" IS 'ShippingState';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."PC_SLS_RTN" IS 'ShippingZipCode';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."EXTN_PC_SLS_RTN" IS '@Deprecated(since 13.1)=ShippingZipCodeExt';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."CO_SLS_RTN" IS 'ShippingCountry';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."TY_PHN" IS 'PhoneType';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."TA_CNCT" IS '@Deprecated(since 13.1)=ContactAreaTelephoneCode';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."TL_CNCT" IS 'ContactLocalTelephoneNumber';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."EXT_CNCT" IS 'ContactExtension';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."ID_SHP_MTH" IS 'ShippingMethodID';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."SHP_CRR" IS 'ShippingCarrier';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."SHP_TYP" IS 'ShippingType';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."SHP_BS_CHG" IS 'ShippingBaseCharge';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."SHP_CHG_RT_BY_WT" IS 'ShippingWeightBasedCharge';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."FLT_RT" IS 'FlatRate';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."SPL_INSTRC" IS 'SpecialInstruction';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."SHP_CHG" IS 'ShippingCharge';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."ID_GP_TX" IS 'TaxGroupID';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."MO_TX" IS 'TaxAmount';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."MO_TX_INC" IS 'InclusiveTaxAmount';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."FL_EXT_SHP" IS 'ExternalShippingFlag';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."TS_CRT_RCRD" IS 'RecordCreatedTimestamp';
 
   COMMENT ON COLUMN "SHP_RDS_SLS_RTN"."TS_MDF_RCRD" IS 'RecordLastModifiedTimestamp';
 
   COMMENT ON TABLE "SHP_RDS_SLS_RTN"  IS 'SaleReturnShippingRecords';
 
   ALTER TABLE "SHP_RDS_SLS_RTN" ADD PRIMARY KEY ("ID_STR_RT", "ID_WS", "DC_DY_BSN", "AI_TRN", "CNT_SND_LAB");

   
   
   
 COMMIT;  