//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 12:39:35 PM IST 
//


package com.oms.order.formatter.schema.invoiceout;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oms.formatter.schema.invoiceout package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oms.formatter.schema.invoiceout
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public InvoiceOutMessage createMessage() {
        return new InvoiceOutMessage();
    }

    /**
     * Create an instance of {@link Message.InvoiceHeader }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader createMessageInvoiceHeader() {
        return new InvoiceOutMessage.InvoiceHeader();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos createMessageInvoiceHeaderInvoiceShipTos() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo createMessageInvoiceHeaderInvoiceShipTosInvoiceShipTo() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetails() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetail() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCosts }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCosts createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailInvoiceDetailCosts() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCosts();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCharges }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCharges createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailInvoiceDetailCharges() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCharges();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailPayMethods }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailPayMethods createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailInvoiceDetailPayMethods() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailPayMethods();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.UPCs }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.UPCs createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailUPCs() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.UPCs();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailOrderDetail() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.StoredValueCards }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.StoredValueCards createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailOrderDetailStoredValueCards() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.StoredValueCards();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderDetailCoupons }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderDetailCoupons createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailOrderDetailOrderDetailCoupons() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderDetailCoupons();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderLineMessages }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderLineMessages createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailOrderDetailOrderLineMessages() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderLineMessages();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToOrderShipTo() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderAdditionalCharges }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderAdditionalCharges createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToOrderShipToOrderAdditionalCharges() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderAdditionalCharges();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.Certficates }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.Certficates createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToOrderShipToCertficates() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.Certficates();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderMessages }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderMessages createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToOrderShipToOrderMessages() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderMessages();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoicePaymentMethods }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoicePaymentMethods createMessageInvoiceHeaderInvoicePaymentMethods() {
        return new InvoiceOutMessage.InvoiceHeader.InvoicePaymentMethods();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.CompanyAddress }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.CompanyAddress createMessageInvoiceHeaderCompanyAddress() {
        return new InvoiceOutMessage.InvoiceHeader.CompanyAddress();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.OrderHeader }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.OrderHeader createMessageInvoiceHeaderOrderHeader() {
        return new InvoiceOutMessage.InvoiceHeader.OrderHeader();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.CustomerSoldTo }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.CustomerSoldTo createMessageInvoiceHeaderCustomerSoldTo() {
        return new InvoiceOutMessage.InvoiceHeader.CustomerSoldTo();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.CustomerBillTo }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.CustomerBillTo createMessageInvoiceHeaderCustomerBillTo() {
        return new InvoiceOutMessage.InvoiceHeader.CustomerBillTo();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceBillingAddress }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceBillingAddress createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceBillingAddress() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceBillingAddress();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceShippingAddress }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceShippingAddress createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceShippingAddress() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceShippingAddress();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.CustomerShipTo }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.CustomerShipTo createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToCustomerShipTo() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.CustomerShipTo();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCosts.InvoiceDetailCost }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCosts.InvoiceDetailCost createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailInvoiceDetailCostsInvoiceDetailCost() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCosts.InvoiceDetailCost();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCharges.InvoiceDetailCharge }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCharges.InvoiceDetailCharge createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailInvoiceDetailChargesInvoiceDetailCharge() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailCharges.InvoiceDetailCharge();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailPayMethods.InvoiceDetailPayMethod }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailPayMethods.InvoiceDetailPayMethod createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailInvoiceDetailPayMethodsInvoiceDetailPayMethod() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.InvoiceDetailPayMethods.InvoiceDetailPayMethod();
    }

    /**
     * Create an instance of {@link InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.UPCs.UPC }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.UPCs.UPC createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailUPCsUPC() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.UPCs.UPC();
    }

    /**
     * Create an instance of {@link Message.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.StoredValueCards.StoredValueCard }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.StoredValueCards.StoredValueCard createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailOrderDetailStoredValueCardsStoredValueCard() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.StoredValueCards.StoredValueCard();
    }

    /**
     * Create an instance of {@link Message.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderDetailCoupons.OrderDetailCoupon }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderDetailCoupons.OrderDetailCoupon createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailOrderDetailOrderDetailCouponsOrderDetailCoupon() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderDetailCoupons.OrderDetailCoupon();
    }

    /**
     * Create an instance of {@link Message.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderLineMessages.OrderLineMessage }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderLineMessages.OrderLineMessage createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToInvoiceDetailsInvoiceDetailOrderDetailOrderLineMessagesOrderLineMessage() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.InvoiceDetails.InvoiceDetail.OrderDetail.OrderLineMessages.OrderLineMessage();
    }

    /**
     * Create an instance of {@link Message.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderAdditionalCharges.OrderAdditionalCharge }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderAdditionalCharges.OrderAdditionalCharge createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToOrderShipToOrderAdditionalChargesOrderAdditionalCharge() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderAdditionalCharges.OrderAdditionalCharge();
    }

    /**
     * Create an instance of {@link Message.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.Certficates.Certificate }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.Certficates.Certificate createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToOrderShipToCertficatesCertificate() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.Certficates.Certificate();
    }

    /**
     * Create an instance of {@link Message.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderMessages.OrderMessage }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderMessages.OrderMessage createMessageInvoiceHeaderInvoiceShipTosInvoiceShipToOrderShipToOrderMessagesOrderMessage() {
        return new InvoiceOutMessage.InvoiceHeader.InvoiceShipTos.InvoiceShipTo.OrderShipTo.OrderMessages.OrderMessage();
    }

    /**
     * Create an instance of {@link Message.InvoiceHeader.InvoicePaymentMethods.InvoicePaymentMethod }
     * 
     */
    public InvoiceOutMessage.InvoiceHeader.InvoicePaymentMethods.InvoicePaymentMethod createMessageInvoiceHeaderInvoicePaymentMethodsInvoicePaymentMethod() {
        return new InvoiceOutMessage.InvoiceHeader.InvoicePaymentMethods.InvoicePaymentMethod();
    }

}
