//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.10 at 09:22:56 AM IST 
//


package com.oms.order.formatter.schema.pickout;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oms.order.formatter.schema.pickout package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oms.order.formatter.schema.pickout
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PickOutMessage }
     * 
     */
    public PickOutMessage createMessage() {
        return new PickOutMessage();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader }
     * 
     */
    public PickOutMessage.PickHeader createMessagePickHeader() {
        return new PickOutMessage.PickHeader();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OtherDetails }
     * 
     */
    public PickOutMessage.PickHeader.OtherDetails createMessagePickHeaderOtherDetails() {
        return new PickOutMessage.PickHeader.OtherDetails();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OtherDetails.OtherDetail }
     * 
     */
    public PickOutMessage.PickHeader.OtherDetails.OtherDetail createMessagePickHeaderOtherDetailsOtherDetail() {
        return new PickOutMessage.PickHeader.OtherDetails.OtherDetail();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherOrderDetailMessages }
     * 
     */
    public PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherOrderDetailMessages createMessagePickHeaderOtherDetailsOtherDetailOtherOrderDetailMessages() {
        return new PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherOrderDetailMessages();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem }
     * 
     */
    public PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem createMessagePickHeaderOtherDetailsOtherDetailOtherItem() {
        return new PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU }
     * 
     */
    public PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU createMessagePickHeaderOtherDetailsOtherDetailOtherItemOtherSKU() {
        return new PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU.OtherUPCs }
     * 
     */
    public PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU.OtherUPCs createMessagePickHeaderOtherDetailsOtherDetailOtherItemOtherSKUOtherUPCs() {
        return new PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU.OtherUPCs();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails createMessagePickHeaderPickDetails() {
        return new PickOutMessage.PickHeader.PickDetails();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail createMessagePickHeaderPickDetailsPickDetail() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.PickDetailMsgs }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.PickDetailMsgs createMessagePickHeaderPickDetailsPickDetailPickDetailMsgs() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.PickDetailMsgs();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.Item }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.Item createMessagePickHeaderPickDetailsPickDetailItem() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.Item();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU createMessagePickHeaderPickDetailsPickDetailItemSKU() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU.UPCs }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU.UPCs createMessagePickHeaderPickDetailsPickDetailItemSKUUPCs() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU.UPCs();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.PickLocations }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.PickLocations createMessagePickHeaderPickDetailsPickDetailPickLocations() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.PickLocations();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickHeaderMsgs }
     * 
     */
    public PickOutMessage.PickHeader.PickHeaderMsgs createMessagePickHeaderPickHeaderMsgs() {
        return new PickOutMessage.PickHeader.PickHeaderMsgs();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OrderPayments }
     * 
     */
    public PickOutMessage.PickHeader.OrderPayments createMessagePickHeaderOrderPayments() {
        return new PickOutMessage.PickHeader.OrderPayments();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.CustomerSoldToAddress }
     * 
     */
    public PickOutMessage.PickHeader.CustomerSoldToAddress createMessagePickHeaderCustomerSoldToAddress() {
        return new PickOutMessage.PickHeader.CustomerSoldToAddress();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.CustomerBillToAddress }
     * 
     */
    public PickOutMessage.PickHeader.CustomerBillToAddress createMessagePickHeaderCustomerBillToAddress() {
        return new PickOutMessage.PickHeader.CustomerBillToAddress();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OrderHeader }
     * 
     */
    public PickOutMessage.PickHeader.OrderHeader createMessagePickHeaderOrderHeader() {
        return new PickOutMessage.PickHeader.OrderHeader();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OrderShipTo }
     * 
     */
    public PickOutMessage.PickHeader.OrderShipTo createMessagePickHeaderOrderShipTo() {
        return new PickOutMessage.PickHeader.OrderShipTo();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherOrderDetailMessages.OtherOrderDetailMessage }
     * 
     */
    public PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherOrderDetailMessages.OtherOrderDetailMessage createMessagePickHeaderOtherDetailsOtherDetailOtherOrderDetailMessagesOtherOrderDetailMessage() {
        return new PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherOrderDetailMessages.OtherOrderDetailMessage();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU.OtherUPCs.OtherUPC }
     * 
     */
    public PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU.OtherUPCs.OtherUPC createMessagePickHeaderOtherDetailsOtherDetailOtherItemOtherSKUOtherUPCsOtherUPC() {
        return new PickOutMessage.PickHeader.OtherDetails.OtherDetail.OtherItem.OtherSKU.OtherUPCs.OtherUPC();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.OrderDetail }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.OrderDetail createMessagePickHeaderPickDetailsPickDetailOrderDetail() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.OrderDetail();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.PickDetailMsgs.PickDetailMsg }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.PickDetailMsgs.PickDetailMsg createMessagePickHeaderPickDetailsPickDetailPickDetailMsgsPickDetailMsg() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.PickDetailMsgs.PickDetailMsg();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU.UPCs.UPC }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU.UPCs.UPC createMessagePickHeaderPickDetailsPickDetailItemSKUUPCsUPC() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.Item.SKU.UPCs.UPC();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickDetails.PickDetail.PickLocations.PickLocation }
     * 
     */
    public PickOutMessage.PickHeader.PickDetails.PickDetail.PickLocations.PickLocation createMessagePickHeaderPickDetailsPickDetailPickLocationsPickLocation() {
        return new PickOutMessage.PickHeader.PickDetails.PickDetail.PickLocations.PickLocation();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.PickHeaderMsgs.PickHeaderMsg }
     * 
     */
    public PickOutMessage.PickHeader.PickHeaderMsgs.PickHeaderMsg createMessagePickHeaderPickHeaderMsgsPickHeaderMsg() {
        return new PickOutMessage.PickHeader.PickHeaderMsgs.PickHeaderMsg();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.OrderPayments.OrderPayment }
     * 
     */
    public PickOutMessage.PickHeader.OrderPayments.OrderPayment createMessagePickHeaderOrderPaymentsOrderPayment() {
        return new PickOutMessage.PickHeader.OrderPayments.OrderPayment();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.CustomerSoldToAddress.Originator }
     * 
     */
    public PickOutMessage.PickHeader.CustomerSoldToAddress.Originator createMessagePickHeaderCustomerSoldToAddressOriginator() {
        return new PickOutMessage.PickHeader.CustomerSoldToAddress.Originator();
    }

    /**
     * Create an instance of {@link PickOutMessage.PickHeader.CustomerSoldToAddress.Placer }
     * 
     */
    public PickOutMessage.PickHeader.CustomerSoldToAddress.Placer createMessagePickHeaderCustomerSoldToAddressPlacer() {
        return new PickOutMessage.PickHeader.CustomerSoldToAddress.Placer();
    }

}
